In [2]:
#EDA--Google Play Store Project
import pandas as pd
import numpy as np

In [3]:
pd.set_option("display.max_columns",None)

df=pd.read_csv("C:\\Naresh it\\Data science KV Rao\\NOTES DAY-32\\googleplaystore.csv")
print(df)

In [5]:
#Find the Number of apps in Google Play Store
print("Number of apps in Google Play Store=",df.shape[0])

Number of apps in Google Play Store= 10841

In [6]:
#Find the Number of Columns of app in Google Play Store
print("Number of Columns of app in Google play Store=",df.shape[1])

Number of Columns of app in Google play Store= 13

In [8]:
#Display Top 5 Rows of The Dataset
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [10]:
#Display Top 3 Rows of The Dataset
df.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [11]:
#2. Check the Last 3 Rows of The Dataset
df.tail(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [12]:
#2. Check the Last 5 Rows of The Dataset
df.tail(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [13]:
#3. Find Shape of Our Dataset (Number of Rows & Number of Columns)
df.shape

(10841, 13)

In [14]:
#4. Get Information About Our Dataset Like Total Number Rows, Total Number
# Datatypes of Each Column And Memory Requirement
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [15]:
#5. Get Overall Statistics About The Dataframe
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [16]:
df.describe(include='all')   # Gives Descriptive statistical Information of

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.describe(include='object')    # Gives Descriptive statistical Information of all Columns with type object

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,10040,8714,842,326,1459,2451

In [19]:
#6.Find the Name of Apps contains Astrology
#step-0: # Gives all column names

In [21]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [22]:
#6.Find the Name of Apps contains Astrology
#step-1: First find app names
df['App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [23]:
#6.Find the Name of Apps contains Astrology
#step-2: Find the app names contains Astrology word
df['App'].str.contains("Astrology")     #Given Boolean array

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840     True
Name: App, Length: 10841, dtype: bool

In [24]:
df[df['App'].str.contains("Astrology")]    #case sensitive

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1570,Horoscopes – Daily Zodiac Horoscope and Astrology,LIFESTYLE,4.6,161143,11M,"10,000,000+",Free,0,Everyone 10+,Lifestyle,"June 25, 2018",5.2.4(881),4.0.3 and up
1592,သိင်္ Astrology - Min Thein Kha BayDin,LIFESTYLE,4.7,2225,15M,"100,000+",Free,0,Everyone,Lifestyle,"July 26, 2018",4.2.1,4.0.3 and up
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [25]:
df[df['App'].str.contains("Astrology",case=False)]      # Ingore the Case

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1570,Horoscopes – Daily Zodiac Horoscope and Astrology,LIFESTYLE,4.6,161143,11M,"10,000,000+",Free,0,Everyone 10+,Lifestyle,"June 25, 2018",5.2.4(881),4.0.3 and up
1592,သိင်္ Astrology - Min Thein Kha BayDin,LIFESTYLE,4.7,2225,15M,"100,000+",Free,0,Everyone,Lifestyle,"July 26, 2018",4.2.1,4.0.3 and up
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [26]:
df[df['App'].str.contains("Astrology",case=False)]  ['App']

1570     Horoscopes – Daily Zodiac Horoscope and Astrology
1592                သိင်္ Astrology - Min Thein Kha BayDin
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, dtype: object

In [27]:
#Step-4: Find the Number of column Names starts with "Astrology"
len(df[df["App"].str.contains("Astrology",case=False)])

3

In [28]:
#7. Find Average App Rating
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [29]:
#Step-1: Get all the app rating
df["Rating"]       #Gives all Numerical Values of 'Rating'

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [30]:
#Step-3: Find the mean() of Rating--Called Average App Rating
print("Average Rating all apps=",df["Rating"].mean())

Average Rating all apps= 4.193338315362443

In [31]:
#8.Find the total number of Unique Category
#Step-0: Find the column Name on which we are working
df.columns  # Gives all column names---take 'Category'

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [32]:
#Step-1: Get all the Values of Unique Category
df["Category"]   # Gives all Values of 'Category'

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10836                 FAMILY
10837                 FAMILY
10838                MEDICAL
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 10841, dtype: object

In [34]:
#Step-2: Get the Unique Values of Category
df["Category"].nunique()    #Gives Number of Unique Values of Category----34

34

In [36]:
#9. Find which Category getting Highest Average Rating
#Step-0: Find the column Name on which we are working
df.columns   # Gives all column names---take 'Category'

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [37]:
#Step-1: Separate OR group the category
df.groupby("Category")

In [38]:
#Step-2: Get the Rating of Every Category
df.groupby("Category")["Rating"]

In [41]:
#Step-3: Find the Mean of Rating of Every Category
df.groupby("Category")["Rating"].mean()

Category
1.9                    19.000000
ART_AND_DESIGN          4.358065
AUTO_AND_VEHICLES       4.190411
BEAUTY                  4.278571
BOOKS_AND_REFERENCE     4.346067
BUSINESS                4.121452
COMICS                  4.155172
COMMUNICATION           4.158537
DATING                  3.970769
EDUCATION               4.389032
ENTERTAINMENT           4.126174
EVENTS                  4.435556
FAMILY                  4.192272
FINANCE                 4.131889
FOOD_AND_DRINK          4.166972
GAME                    4.286326
HEALTH_AND_FITNESS      4.277104
HOUSE_AND_HOME          4.197368
LIBRARIES_AND_DEMO      4.178462
LIFESTYLE               4.094904
MAPS_AND_NAVIGATION     4.051613
MEDICAL                 4.189143
NEWS_AND_MAGAZINES      4.132189
PARENTING               4.300000
PERSONALIZATION         4.335987
PHOTOGRAPHY             4.192114
PRODUCTIVITY            4.211396
SHOPPING                4.259664
SOCIAL                  4.255598
SPORTS                  4.223511
TOOLS                   4.047411
TRAVEL_AND_LOCAL        4.109292
VIDEO_PLAYERS           4.063750
WEATHER                 4.244000
Name: Rating, dtype: float64

In [43]:
#Step-4: Find the Highest Average Rating
df.groupby("Category")["Rating"].mean().sort_values(ascending=False)
#Here we get First Entry is the Highest Average Rating

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

In [45]:
df.groupby("Category")["Rating"].mean().sort_values()
#Here we get Last Entry is the Highest Average Rating

Category
DATING                  3.970769
TOOLS                   4.047411
MAPS_AND_NAVIGATION     4.051613
VIDEO_PLAYERS           4.063750
LIFESTYLE               4.094904
TRAVEL_AND_LOCAL        4.109292
BUSINESS                4.121452
ENTERTAINMENT           4.126174
FINANCE                 4.131889
NEWS_AND_MAGAZINES      4.132189
COMICS                  4.155172
COMMUNICATION           4.158537
FOOD_AND_DRINK          4.166972
LIBRARIES_AND_DEMO      4.178462
MEDICAL                 4.189143
AUTO_AND_VEHICLES       4.190411
PHOTOGRAPHY             4.192114
FAMILY                  4.192272
HOUSE_AND_HOME          4.197368
PRODUCTIVITY            4.211396
SPORTS                  4.223511
WEATHER                 4.244000
SOCIAL                  4.255598
SHOPPING                4.259664
HEALTH_AND_FITNESS      4.277104
BEAUTY                  4.278571
GAME                    4.286326
PARENTING               4.300000
PERSONALIZATION         4.335987
BOOKS_AND_REFERENCE     4.346067
ART_AND_DESIGN          4.358065
EDUCATION               4.389032
EVENTS                  4.435556
1.9                    19.000000
Name: Rating, dtype: float64

In [47]:
df.groupby("Category")["Rating"].mean().sort_values()
#Here we get Last Entry is the Highest Average Rating

Category
DATING                  3.970769
TOOLS                   4.047411
MAPS_AND_NAVIGATION     4.051613
VIDEO_PLAYERS           4.063750
LIFESTYLE               4.094904
TRAVEL_AND_LOCAL        4.109292
BUSINESS                4.121452
ENTERTAINMENT           4.126174
FINANCE                 4.131889
NEWS_AND_MAGAZINES      4.132189
COMICS                  4.155172
COMMUNICATION           4.158537
FOOD_AND_DRINK          4.166972
LIBRARIES_AND_DEMO      4.178462
MEDICAL                 4.189143
AUTO_AND_VEHICLES       4.190411
PHOTOGRAPHY             4.192114
FAMILY                  4.192272
HOUSE_AND_HOME          4.197368
PRODUCTIVITY            4.211396
SPORTS                  4.223511
WEATHER                 4.244000
SOCIAL                  4.255598
SHOPPING                4.259664
HEALTH_AND_FITNESS      4.277104
BEAUTY                  4.278571
GAME                    4.286326
PARENTING               4.300000
PERSONALIZATION         4.335987
BOOKS_AND_REFERENCE     4.346067
ART_AND_DESIGN          4.358065
EDUCATION               4.389032
EVENTS                  4.435556
1.9                    19.000000
Name: Rating, dtype: float64

In [49]:
#10.Find the total number App having 5 star Rating Apps
#Step-0: Find the column Name on which we are working
print(df.columns)    #Gives all column names--takes 'Rating'
print("------------------------------")
#Step-1:Find the Rating Values
print(df["Rating"])
print("-------------------------------")

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')
------------------------------
0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64
-------------------------------

In [50]:
#Step-2: Find the Rating Values which is equal to 5
df["Rating"]==5    #Gives Boolean Values

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837     True
10838    False
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [54]:
#Step-3: Get the App names by Passing the Boolean Values to DataFrame
df[df["Rating"]==5]       #Gives 5 star Rating app names

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15,37M,"1,000+",Free,0,Everyone,Comics,"June 26, 2018",2.0,4.0.3 and up
612,American Girls Mobile Numbers,DATING,5.0,5,4.4M,"1,000+",Free,0,Mature 17+,Dating,"July 17, 2018",3.0,4.0.3 and up
615,Awake Dating,DATING,5.0,2,70M,100+,Free,0,Mature 17+,Dating,"July 24, 2018",2.2.9,4.4 and up
633,Spine- The dating app,DATING,5.0,5,9.3M,500+,Free,0,Teen,Dating,"July 14, 2018",4.0,4.0.3 and up
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6,5.0M,100+,Free,0,Mature 17+,Dating,"August 1, 2018",8.2,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14,16M,100+,Free,0,Everyone,Arcade,"June 19, 2017",2.5a,4.1 and up
10742,GKPB FP Online Church,LIFESTYLE,5.0,32,7.9M,"1,000+",Free,0,Everyone,Lifestyle,"December 31, 2017",0.7.1,4.4 and up
10776,Monster Ride Pro,GAME,5.0,1,24M,10+,Free,0,Everyone,Racing,"March 5, 2018",2.0,2.3 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up

In [55]:
#Step-3: Get the App names by Passing the Boolean Values to DataFrame
df[df["Rating"]==5]["App"]   # Gives 5 star Rating App Names

329                    Hojiboy Tojiboyev Life Hacks
612                   American Girls Mobile Numbers
615                                    Awake Dating
633                           Spine- The dating app
636      Girls Live Talk - Free Text and Video Chat
                            ...
10721                             Mad Dash Fo' Cash
10742                         GKPB FP Online Church
10776                              Monster Ride Pro
10820                               Fr. Daoud Lamei
10837              Fr. Mike Schmitz Audio Teachings
Name: App, Length: 274, dtype: object

In [56]:
#Step-4: Get Total Number of App names having 5 star rating
len(df[df["Rating"]==5])     # Gives Number of 5 star Rating Apps

274

In [2]:

import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Naresh it\\Data science KV Rao\\NOTES DAY-32\\googleplaystore.csv")
print(df)

                                                     App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0
1         3.9     967                 14M     500,000+  Free     0
2         4.7   87510                8.7M   5,000,000+  Free     0
3         4.5  215644                 25M  50,000,000+  Free     0
4         4.3     967                2.8M     100,000+  Free     0
...       ...     ...                 ...          ...   ...   ...
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018
1           Everyone  Art & Design;Pretend Play  January 15, 2018
2           Everyone               Art & Design    August 1, 2018
3               Teen               Art & Design      June 8, 2018
4           Everyone    Art & Design;Creativity     June 20, 2018
...              ...                        ...               ...
10836       Everyone                  Education     July 25, 2017
10837       Everyone                  Education      July 6, 2018
10838       Everyone                    Medical  January 20, 2017
10839     Mature 17+          Books & Reference  January 19, 2015
10840       Everyone                  Lifestyle     July 25, 2018

              Current Ver         Android Ver
0                   1.0.0        4.0.3 and up
1                   2.0.0        4.0.3 and up
2                   1.2.4        4.0.3 and up
3      Varies with device          4.2 and up
4                     1.1          4.4 and up
...                   ...                 ...
10836                1.48          4.1 and up
10837                 1.0          4.1 and up
10838                 1.0          2.2 and up
10839  Varies with device  Varies with device
10840  Varies with device  Varies with device

[10841 rows x 13 columns]

In [3]:
nor=0
for appname in df[df["Rating"]==5] ["App"]:
    print(appname)
    nor=nor+1
print("Number of Apps with 5 star Rating=",nor)

Hojiboy Tojiboyev Life Hacks
American Girls Mobile Numbers
Awake Dating
Spine- The dating app
Girls Live Talk - Free Text and Video Chat
Online Girls Chat Group
Speeding Joyride & Car Meet App
SUMMER SONIC app
Prosperity
Mindvalley U Tallinn 2018
Eternal life
Super Hearing Secret Voices Recorder PRO
FHR 5-Tier 2.0
Sway Medical
Labs on Demand
Dermatology Atlas (Colored & Illustrative)
Tablet Reminder
Galaxies of Hope
KBA-EZ Health Guide
FoothillsVet
PrimeDelivery
You're an Anime
Anatomy & Physiology Vocabulary Exam Review App
NCLEX Multi-topic Nursing Exam Review-Quiz & notes
Basics of Orthopaedics
Clinic Doctor EHr
Sway Medical
420 BZ Budeze Delivery
BP Journal - Blood Pressure Diary
Zen Leaf
ADS-B Driver
P-Home for KLWP
Android P Style Icon Pack
R Programing Offline Tutorial
Easy Hotspot Ad Free
Tafsiir Quraan MP3 Af Soomaali Quraanka Kariimka
Lakeside AG Moultrie
Eternal Light AG
Ag Valley Cooperative
Chenoweth AH
Arrowhead AH App
Kimbrough AH
AI Today : Artificial Intelligence News & AI 101
AJ Cam
Hey AJ! It's Saturday!
Selfie With Champion AJ Style
AJ RETAILS
Hey AJ! It's Bedtime!
AJ Men's Grooming
AJ Gray Dark Icon Pack
AJ Blue Icon Pack
AJ Rafael Music Lessons
AP® Guide
meStudying: AP English Lit
AP Art History Flashcards
AQ Ria Retail
Accounting Quiz (AQ) Malaysia
Wowkwis aq Ka'qaquj
Jobs in Canada - Emplois au Canada
Tozer Devotional -Series 1
Food-Aw - Order Food Online in Aruba
Axe Champs! Wars
Flippy Axe : Flip The Knife & Axe Simulator
A-Y Collection
Quran Khmer Offline AY
Ra Ga Ba
BC MVA Fines
Railroad Radio Vancouver BC
iCard BD Plus
Exam Result BD
Helping BD
Movement BE
ReactNative BG Geolocation
BG Guide
Bh Public School
Barbers.BH
BI News
Propel BI APP
BI APP
HON. B.J. ACS COLLEGE ALE
BJ Foods
Read it easy for BK
BK Video Status
BK Formula Calculator
Dr Bk Sachin bhai
BK Arogyam Task Track
Bk Usha behn
BK Gold App
BL Flowers Digital
BM SPM Practice
BM Physiotherapy Clinic
BM speed test
BP Journal - Blood Pressure Diary
BP Log lite
MI-BP
Bar-B-Q Rib House
Brick Breaker BR
COMSATS BOOK STORE FOR BS(CS)
BS-Mobile
Wifi BT Scanner
Jabbla BT
BU Study
Barisal University App-BU Face
Catholic La Bu Zo Kam
BV Mobile Apps
BV
BV Sridhara Maharaj
Bacterial vaginosis Treatment - Sexual disease
BxPort - Bitcoin Bx (Thailand)
420 BZ Budeze Delivery
CA Speakers
CB Fit
CB VIDEO VISION
C B Patel Health Club
CB News
CB Register
Cb browser
CB Heroes
CD CHOICE TUBE
Yazdani Cd Center EllahAbad Official App
CE Smart
TI-84 CE Graphing Calculator Manual TI 84
MCQ CE IT
CF Life
Unity CF
Overcomers CF - GA
CF
CF Townsville
CG Prints
CG FM
CG - Chemistry free
CG Jobs
Startupticker.ch News, Events
CI 174 Gray Icon Pack
Trovami se ci riesci
Nur təfsiri 1-ci cild
CJ Gospel Hour
CJ'S TIRE AND AUTO INC.
The CJ Rubric
CJ's Coffee Cafe
Sir C J New Primary School
CJ the REALTOR
211:CK
USMLE Step 2 CK Flashcards
CK Employee Portal
Tic Tac CK
CL REPL
CL Keyboard - Myanmar Keyboard (No Ads)
CL Notifier
Color CL
CL Strength
CN Resident
Foothills CP
CP Installer App
CP Trivia
CQ ESPM
CricQuick
iReadMe
Cr Aviation Academy
CR Tracker for Chests
CS & IT Interview Questions
CT Brain Interpretation
CT Cervical Spine
CARDIAC CT TECHNIQUE
Dine In CT - Food Delivery
CT Checkout
Morse Player
30WPM Amateur ham radio Koch CW Morse code trainer
Oración CX
cx advance call blocker
NOMISMA.com.cy by FMW
Cy-Fair VFD EMS Protocols
Cy-Fair Christian Church
CZ-Help
CZ Kompas
DB HOME
DB Pickles
Superheroes, Marvel, DC, Comics, TV, Movies News
DC N COMPANY ENTERTAINMENT RADIO!
DC-014
AC DC Power Monitor
The Divine Feminine App: the DF App
DF Glue Board
DG-App
Free coupons and vouchers
DG OFF - 100% Free Coupons & Deals
DG TV
DH-UFO
D-H Pharmacy
PK and DK Audio App
DL Image Manager
DM Buddy » Learn Digital Marketing
Disciple Maker’s (DM) Lab
DN Blog
DN Employee
DN Calculators
WPBS-DT
DT CLOTHINGS
Dt. Jyothi Srinivas
Spring flowers theme couleurs d t space
DV ASSIST
DV Youth
DW Security
DW Timer
RETRO Shocked DW-6000
Chronolink DX
Santa's Monster Shootout DX
Cloud DX Connected Health
DYPSOET
chat dz
i am EB
EB Scanner
UP EB Bill Payment & Details
EB Cash Collections
EC Calgary
Victoria EC
EC SPORTS
EC Fairgrounds
EC Mover
EF Events
EF Forms
EF App
EF Academy
EG India
Eh Bee Wallpapers HD
NEMA ei
ei Calc
Kolkata News:Anandbazar Patrika,ei samay&AllRating
EJ messenger
Master E.K
EK Bailey Preaching Conference
Pyaar Ek Dhoka
Ek Bander Ne Kholi Dukan
Hum Ek Hain 2.02
Ek Vote
Asha Ek Hope - ALS/ MND
Ek Qissa He Quran Se (Qurani Waqiyat)
Lyrics of Ek Paheli Leela
Shabad Gurubani Punjabi mp3 free - Ek Onkar Satnam
FAST EO
EP Church Annapolis
EP Radio
ER Assist
Dr. ES PV Calculator
ES Billing System (Offline App)
ES Solar
EU Exit poll
daskal.eu
FA Player Essentials
Noticias FC Barcelona
Story Time FD
FD Calculator (EMI, SIP, RD & Loan Eligilibility)
Comunidad De Fe Minitries
Safe Santa Fe
Santa Fe Thrive
Ríos de Fe
Jigsaw Volvo FH 16 Trucks
FH School
FK CLASSIC FOR YOU
FK Dedinje BGD
South Florida AA Meetings
Trinity Church Deltona, FL
Beacon Baptist Jupiter, FL
Florida Beach Wallpapers HD
Florida Wildflowers
Wallpapers FN SCAR H
FN
FO Bixby
Mu.F.O.
Mad Dash Fo' Cash
GKPB FP Online Church
Monster Ride Pro
Fr. Daoud Lamei
Fr. Mike Schmitz Audio Teachings
Number of Apps with 5 star Rating= 274

In [4]:
#Step-2: Find the data type of review column
print(df["Reviews"].dtype)  #given dtype(0) OR object type

object

In [5]:
#Step-3: Convert Dtype of df["Review"] as int or float by using astype()
#df["Reviews"].astype("float")--- # gives ValueError bcoz one col contain

In [6]:
#Step-4: Find which App review Value is 3.0M
df["Reviews"]=="3.0M"  #given boolean array

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10841, dtype: bool

In [7]:
#Step-4: Find which App review Value is 3.0M
df[df["Reviews"]=="3.0M"][["App","Reviews"]]       #Given apps with 3.0M

                                           App Reviews
10472  Life Made WI-Fi Touchscreen Photo Frame    3.0M

In [8]:
#Step-5: Replace 3.0M Value with 3.0 with replace() of DataFrame
df["Reviews"]=df["Reviews"].replace("3.0M",3.0)    #Get replace and modified

In [9]:
df.loc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                               3.0
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [10]:
#Step-6: Now Again Convert dtype(o) of df["Review"] to float type by usin
#df["Review"].astype("float") #Dtype changed and Modify its dtype permane
df["Reviews"]=df["Reviews"].astype("float")

In [11]:
df["Reviews"].dtype

dtype('float64')

In [12]:
print(df["Reviews"].dtype)

float64

In [13]:
#Step-8: Now to get Average review, we apply mean()
df["Reviews"].mean()

444111.9265750392

In [24]:
#12.Find the total number of Free and Paid Apps of Google Play store
df["Type"]

0        Free
1        Free
2        Free
3        Free
4        Free
         ...
10836    Free
10837    Free
10838    Free
10839    Free
10840    Free
Name: Type, Length: 10841, dtype: object

In [26]:
len(df[df["Type"]=="Free"])

10039

In [27]:
len(df[df["Type"]=="Paid"])

800

In [1]:
#Step-3: Now the total number of Free and Paid Apps of Google Play store
df["Type"].value_counts()  #Gives the result

NameError: name 'df' is not defined